### ISSUE TITLE
Not compatible with mlr3 package and DALEXtra package

### ISSUE THREAD

**Issue by zhangkaicr** [ModelOriented/shapviz#124]
Thanks to your shapviz package, we can do many beautiful visualizations of shap values in the R environment. Since there are many current machine learning algorithms, everyone tends to use a system with a unified wrapper, such as mlr3. Your shapviz package can construct shapviz objects using the results of the predict_parts function of the DALEXtra package. The DALEXtra package can also build an explainer for the results of mlr3 for the next step of predict_parts calculation. However, I found some problems when applying the above process in practice.

`
# Create explainer from your mlr3 model
titanic_imputed$survived <- as.factor(titanic_imputed$survived)
task_classif <- TaskClassif$new(id = "1", backend = titanic_imputed, target = "survived")
learner_classif <- lrn("classif.rpart", predict_type = "prob")
learner_classif$train(task_classif)
exp3<- explain_mlr3(learner_classif, data = titanic_imputed,
             y = as.numeric(as.character(titanic_imputed$survived)))

# Instance Level shap of the Model Predictions
pred_part3<- DALEX::predict_parts(explainer = exp3,
                                  new_observation = titanic_imputed[,1:7],
                                  type = "shap")

# Initialize "shapviz" Object
sv <- shapviz(pred_part3)

# SHAP Importance Plots
sv_importance(sv,kind = "beeswarm")`

![image](https://github.com/ModelOriented/shapviz/assets/74847937/3008fc70-8119-4929-9649-0c88af00bd0a)

**Comment by zhangkaicr** [comment]
After inspection, we found that the result of the shapviz object only has one row of data

![image](https://github.com/ModelOriented/shapviz/assets/74847937/dd00c6bd-21b3-4c1b-8346-96cfebdb68bc)

**Comment by mayer79** [comment]
You are perfectly right: The DALEX/shapviz combo focusses on **local** explanations via `sv_waterfall()` and `sv_force()`.

Since you want to visualize SHAP decompositions of multiple observations, you might want to do the actual crunching via {kernelshap}. It has an exact permutation SHAP algo (for not too many features), and Kernel SHAP as strong approximation.

Note: Explanations are done on probability scale here. I usually recommend to do it on log-odds scale, which is easily possible by providing also a taylored  `pred_fun()` to `permshap()/kernelshap()`:

```r
X_explain <- titanic_imputed[sample(nrow(titanic_imputed), 500), ]
ps <- permshap(
  learner_classif, 
  X = X_explain, 
  bg_X = X_explain[1:200, ],
  feature_names = learner_classif$selected_features()
)
# Or kernelshap() if number of features is larger than ~ 8-10
sv <- shapviz(ps)[[1]]  # for binary classification, choose second class
sv

sv_importance(sv, "bee")
sv_dependence(sv, x)
```
<img width="278" alt="image" src="https://github.com/ModelOriented/shapviz/assets/16206095/6bbe5e98-74c6-493a-adbd-205c074f7470">

<img width="850" alt="image" src="https://github.com/ModelOriented/shapviz/assets/16206095/00c1fcb0-dc49-4351-877e-870b459d075e">

**Comment by mayer79** [comment]
Same on logit scale:

```r
ps_logit <- permshap(
  learner_classif, 
  X = X_explain, 
  bg_X = X_explain[1:200, ],
  feature_names = learner_classif$selected_features(),
  pred_fun = function(m, X) qlogis(m$predict_newdata(X)$prob[, 2])
)
# Or kernelshap() if number of features is larger than ~ 8-10
sv_logit <- shapviz(ps_logit)
sv_logit

sv_importance(sv_logit, "bee")
sv_dependence(sv_logit, x)
```

<img width="275" alt="image" src="https://github.com/ModelOriented/shapviz/assets/16206095/9ef62592-255a-4cff-9e07-ec203aeb8f37">

<img width="781" alt="image" src="https://github.com/ModelOriented/shapviz/assets/16206095/a28bacff-2ef6-48dd-b2ac-30ba76505f6b">

**Comment by zhangkaicr** [comment]
> kernelshap

Thank you very much for your answer.

**Comment by zhangkaicr** [comment]
Thank you very much for your answer. I have studied your kernelshap package carefully and it is indeed a very good solution. But when the independent variables of the visual shape need to be more than 14, is there a way to achieve it?

**Comment by mayer79** [comment]
In what function? For dependence plots, you can select, e.g., four features at a time to not overload each plot. 

Beeswarm summary plots are somewhat limited regarding the number of features, but you can make the plot very high to fit more features in.

**Comment by mayer79** [comment]
Btw, thx to your question, I found a way to greatly simplify the internal {mlr3} wrapper of {kernelshap}!
