### ISSUE TITLE
Baseline-value question

### ISSUE THREAD

**Issue by alkat19** [ModelOriented/shapviz#138]
Hey there!

Maybe I have missed it in the vignette, but what is the output of the get_baseline function? Is it the mean prediction of the model in the dataset you extract the shap values in the log-odds scale?  For some reason I see some differences between the average prediction of my XGBoost model and the output of the get_baseline function (after I transform to probability). However, when I use the explain function from DALEX and plot the contributions for a single observation, then the E[f(x)] corresponds perfectly with the mean prediction of the model, as extracted from the explainer.

Thank you in advance!

**Comment by mayer79** [comment]
Hello. 

The sum of the SHAP values of one observation equals the prediction minus that baseline. 

For an XGBoost model evaluated with its internal TreeSHAP implementation, the predictions (and the baseline) are on "raw" scale, in your case on logit scale. They can't be mapped to probability scale without violating one of the fairness axioms. The mapped values are no SHAP values anymore.

When you calculate SHAP values directly with DALEX, it either uses the breakdown algorithm or KernelSHAP. Both algorithms can produce values on any scale, in your case on probability scale. This explains the difference.

(Additivity on probability scale is a very unnatural property, so I would rather work on logit scale.)

**Comment by alkat19** [comment]
Makes perfect sense, thank you!
