### ISSUE TITLE
Allow data.frame input with categorical features for LightGBM models

### ISSUE THREAD

**Issue by RoyalTS** [ModelOriented/shapviz#147]
This currently fails:

```r
library(tidymodels)
library(bonsai)
library(kernelshap)
library(shapviz)

iris_recipe <- iris %>%
  recipe(Sepal.Length ~ .)

parsnip::boost_tree(
  mode = "regression"
) |>
  parsnip::set_engine(
    "lightgbm",
    verbose = -1
  ) -> lgbm_model


iris_wf <- workflow() %>%
  add_recipe(iris_recipe) %>%
  add_model(lgbm_model)

fit <- iris_wf %>%
  fit(iris)

shap <- shapviz::shapviz(extract_fit_engine(fit), iris[, -1], bg_X = iris)
```

with error message

```
Error in shapviz.lgb.Booster(extract_fit_engine(fit_lgbm), X_pred = orders_pre_sample_baked,  : 
  X_pred must be a matrix
```

Would it be possible to allow for such `data.frame` input including categorical/factor features?

**Comment by mayer79** [comment]
## TreeSHAP

This is the tricky (but faster and better) approach. Note that I have integer encoded Species in the recipe. Maybe there is a way without this?

```
library(tidymodels)
library(bonsai)
library(shapviz)

iris_recipe <- iris %>%
  recipe(Sepal.Length ~ .) |> 
  step_integer(Species)

parsnip::boost_tree(
  mode = "regression"
) |>
  parsnip::set_engine(
    "lightgbm",
    verbose = -1
  ) -> lgbm_model


iris_wf <- workflow() %>%
  add_recipe(iris_recipe) %>%
  add_model(lgbm_model)

fit <- iris_wf %>%
  fit(iris)

X_pred <- bake(
  prep(iris_recipe), 
  has_role("predictor"),
  new_data = iris, 
  composition = "matrix"
)

shap <- shapviz::shapviz(extract_fit_engine(fit), X_pred = X_pred, X = iris)
sv_importance(shap, "bee", show_numbers = TRUE)
```

![image](https://github.com/user-attachments/assets/dcc0995f-aca9-469b-81a4-799fb875feda)

## Model-agnostic SHAP 

Much easier coding (no need to think about any transformations, X_pred etc.), but exponentially slower in general.

library(tidymodels)
library(bonsai)
library(kernelshap)
library(shapviz)

iris_recipe <- iris %>%
  recipe(Sepal.Length ~ .)

parsnip::boost_tree(
  mode = "regression"
) |>
  parsnip::set_engine(
    "lightgbm",
    verbose = -1
  ) -> lgbm_model


iris_wf <- workflow() %>%
  add_recipe(iris_recipe) %>%
  add_model(lgbm_model)

fit <- iris_wf %>%
  fit(iris)

shap <- kernelshap(fit, X = iris) |>   # or permshap() for <= 8 predictors
  shapviz()
sv_importance(shap, "bee", show_numbers = TRUE)

**Comment by mayer79** [comment]
Btw. this is the magic potion that makes our life difficult for TreeSHAP:

```r
bonsai:::prepare_df_lgbm <- function (x, y = NULL) 
{
    categorical_cols <- categorical_columns(x)
    x <- categorical_features_to_int(x, categorical_cols)
    x <- as.matrix(x)
    return(x)
}
```

**Comment by RoyalTS** [comment]
Wow, thanks for the fast response!

Does that mean bonsai actually integer-encodes categoricals silently? Is that not associated with a loss of generality?

**Comment by mayer79** [comment]
The recipe applies the original factor levels to fresh data. Thus, the additional bonsai transformation should be safe at application time.

The suggestion would be:
1. Do explicit integer encodings in the recipe.
2. Specify which of the unordered categoricals should be internally treated as categorical. (Where in Tidymodels would we do this)?
3. Use the logic outlined in the TreeSHAP solution above. It gets complicated mainly if your recipe would do 1:m transformations, like OHE. (But I don't see good reasons for doing so.)

**Comment by RoyalTS** [comment]
> 2. Specify which of the unordered categoricals should be internally treated as categorical. (Where in Tidymodels would we do this)?

It doesn't seem like that's possible. tidymodels insists on handling this internally, without exposing `lgb.train()`s arguments.

**Comment by mayer79** [comment]
Then we can write:

```r
X_pred <- bake(
  prep(iris_recipe), 
  has_role("predictor"),
  new_data = iris
) |>
  bonsai:::prepare_df_lgbm()
```

**Comment by mayer79** [comment]
This seems to be a robust workflow to use LightGBM's TreeSHAP:

```r
library(tidymodels)
library(bonsai)
library(shapviz)

iris_recipe <- iris %>%
  recipe(Sepal.Length ~ .)
 # step_integer(Species)  # For ordered variables and those you don't want to greedily encode by Lgb categoricals

parsnip::boost_tree(
  mode = "regression"
) |>
  parsnip::set_engine(
    "lightgbm",
    verbose = -1
  ) -> lgbm_model


iris_wf <- workflow() %>%
  add_recipe(iris_recipe) %>%
  add_model(lgbm_model)

fit <- iris_wf %>%
  fit(iris)

X_pred <- bake(
  prep(iris_recipe), 
  has_role("predictor"),
  new_data = iris
) |> 
  bonsai:::prepare_df_lgbm()

stopifnot(colnames(X_pred) %in% colnames(iris))

shap <- shapviz::shapviz(extract_fit_engine(fit), X_pred = X_pred, X = iris)
sv_importance(shap, "bee", show_numbers = TRUE)
```

**Comment by RoyalTS** [comment]
That works! Brilliant!

Once again, thank you profusely for the fast response and how deep you got into this to figure it out!

**Comment by mayer79** [comment]
I am adding a vignette to clarify things. Thanks for the good example and for raising the topic.
