### ISSUE TITLE
[DOC] h2o random forests are supported as well!

### ISSUE THREAD

**Issue by mayer79** [ModelOriented/shapviz#163]
We should note this in the docu.

**Comment by mayer79** [comment]
Implemented in #164

**Comment by Famondir** [comment]
Hi, I have a question. Is `shapviz` using the TreeSHAP algorithm if we pass it a h2o random forest? Or does it use Kernel SHAP? I would like to know, if I can speed up my calculations, by using TreeSHAP or it already is the case.

**Comment by mayer79** [comment]
It is using TreeSHAP. Random forest trees are usually quite deep, which leads to memory intensive calculations. Is it too slow?

**Comment by Famondir** [comment]
Thanks for the fast response.

I have no real point to compare it with. I calculate SHAP values for 2000 observations on a random forest with 22 features. Using the standard h2o random forest settings, so ntrees = 50 and  max_depth = 20. So time complexity formula get 2000*50*leafs?*20^2 = 40_000_000*leafs and it takes around 20 minutes on a 2.1 GHz CPU.

It is not crucial thing, I mainly was curious.

**Comment by mayer79** [comment]
Okay. Shapviz actually never calls kernelshap.
