### ISSUE TITLE
Upcoming changes to fastshap

### ISSUE THREAD

**Issue by bgreenwell** [ModelOriented/shapviz#34]
Thanks for this awesome package. I've decided to deprecate the hacky plotting functions in fastshap in favor of using this package. However, a couple of [upcoming changes](https://github.com/bgreenwell/fastshap/blob/master/NEWS.md) in v0.8.0 might require some minor changes to the `shapviz.explain()` method. In short:

* The `explain()` function essentially returns a matrix now, as opposed to a tibble.
* The output from `explain()` now also contains a `"baseline"` attribute, which could be useful to default to in some of the plotting functions.

Looking to update on CRAN sometime mid-November.

**Comment by mayer79** [comment]
Oh, fantastic news. "shapviz" has a couple of dependencies that are not under my control. Still I hope things are stable. 

Some small questions:

- the resulting object is still of class "explain", right?
- is it acceptable for the user to pass feature values not only to fastshap but also to shapviz? An alternative would be to output a list containing the matrix of SHAP values, the baseline, and the feature data frame.

**Comment by bgreenwell** [comment]
Yes, I kept the class output as “explain”. In fact, I’ll test on my end, but your package should still work as is with “explain” objects, it’s just perhaps unnecessary to call data.matrix() or as.matrix() on the output now before passing in. Also not sure if you want to default the baseline argument to grab the baseline attribute for newer package version?

Not sure what you mean with the second point? Was this needed before for one of the plotting functions?

**Comment by mayer79** [comment]
This version should work with the current and the future "fastshap":

```r
shapviz.explain <- function(object, X, baseline = attr(object, "baseline"), collapse = NULL, ...) {
  if (is.null(baseline)) {
    baseline <- 0
  }
  shapviz.matrix(as.matrix(object), X = X, baseline = baseline, collapse = collapse)
}
```

Regarding the second (unclear) point:

I was wondering whether it would be an option to exit from fastshap by doing something along these lines:

```
explain.default <- function() {
  out <- list(phis = phis, baseline = fnull, X = X)
  class(out) <- "explain"
  return(out)
}
```

In this way, the constructor of shapviz would already know everything: SHAP values, baseline, and the feature matrix X.

**Comment by bgreenwell** [comment]
Ahh, I see what you mean. It's possible, my only concern would be storing a copy of `X` if `X` is big. Maybe a `keepX = TRUE`? If it's there then `shapviz` can check whether or not `is.null(output$X)`? If it's a list then I'd also like to add a print method.

**Comment by mayer79** [comment]
I see your point. Actually I think we would need `newdata` to be stored, not `X`.

Returning a list of additional class `explain` has some advantages, but it might break existing code. Hmmm.

**Comment by bgreenwell** [comment]
I think it’s doable, especially since fastshap is still a relatively new package. I think we can add an argument to help with backward compatibility. If not newX, then maybe something like as.matrix=TRUE?

**Comment by mayer79** [comment]
@bgreenwell : I think you could indeed do this interface change:

- An argument like `only_shap_values = FALSE` could be used for backward compatibility, but maybe even with a depreciation warning. 
- The extended interface would contain the matrix of SHAP values, the baseline value, and `newdata` (right?).

In contrast to the CRAN version, the "shapviz" master branch allows the feature data.frame (X) to contain more features than the SHAP matrix. So even if someone would use your `feature_names` argument, passing `newdata` to "shapviz" would be fine. 

Example:

```
library(fastshap)
library(shapviz)

fit <- lm(Sepal.Length ~ Sepal.Width + Petal.Length, data = iris)
shap <- explain(
  fit, 
  X = iris,
  feature_names = c("Sepal.Width", "Petal.Length"),
  newdata = head(iris), 
  nsim = 100, 
  pred_wrapper = predict
)

# We need:
# - 6x2 matrix of SHAP values
# - baseline value
# - 6x? feature data.frame

sv <- shapviz(shap)
```

**Comment by bgreenwell** [comment]
Thanks @mayer79 , sounds reasonable to me. I'll put in a fix shortly!

**Comment by mayer79** [comment]
There are no multi-class plots in "shapviz". 

For multiclass XGB, LGB, and kernelshap objects, you can *select* the class of interest by the argument `which_class`. Technically, this allows to create a "shapviz" object per class and then glue the plots together with "patchwork" package.

**Comment by bgreenwell** [comment]
> Thanks @mayer79 , sounds reasonable to me. I'll put in a fix shortly!

Apparently, shortly never happened. Coming back to several packages that need some love and care. I saw the new release of **shapviz**; I combed through the release notes, but has anything in the package changed that would matter in this thread?

**Comment by mayer79** [comment]
Thanks for coming back to this! No changes done in the connectors so far:

```
shapviz.explain <- function(object, X, baseline = 0, collapse = NULL, ...) {
  shapviz.matrix(
    object = as.matrix(object), X = X, baseline = baseline, collapse = collapse
  )
}
```
This is the (open) PR with the small change regarding the baseline: https://github.com/ModelOriented/shapviz/pull/38/files

**Comment by bgreenwell** [comment]
Hey @mayer79, finally pushed [some changes](https://github.com/bgreenwell/fastshap/blob/devel/NEWS.md) to the [devel branch](https://github.com/bgreenwell/fastshap/tree/devel). In short, I added a new `shap_only` argument, which you can see in [this test file](https://github.com/bgreenwell/fastshap/blob/devel/slowtests/test-shapviz.R), along with a suggestion for modifying `shapviz.explain()`:

```r
shapviz.explain <- function (object, X, baseline = NULL, collapse = NULL, ...) {

  #
  # FIXME: Might need to add some logic in case user is using fastshap <= v0.0.7
  # For example, `if (packageVersion("fastshap") <= "0.0.7") {revert to old behavior} else {do what's suggested below}
  #
  
  if (is.matrix(object)) {  # explain() called with shap_only=TRUE
    if (is.null(baseline)) {  # try to extract baseline attribute
      baseline <- attr(object, which = "baseline")
    }
    if (is.null(baseline)) {  # will still be NULL is missing, so check again
      warning("No baseline attribute found in ", deparse(substitute(object)),
              "; setting baseline to zero.", call. = FALSE)
      baseline <- 0
    }
    shapviz.matrix(object, X = X, baseline = baseline, collapse = collapse)
  } else {  # explain() called with shap_only=FALSE
    shapviz.matrix(object$shapley_values, X = object$feature_values,
                   baseline = object$baseline, collapse = collapse)
  }
}
```

Still working on updating the docs, examples, etc. But let me know what you think. I'd suggest adding **fastshap** to the Enhances field as well. Might need to

**Comment by mayer79** [comment]
Thanks for your suggestion!

We need to catch `object$feature_values` already when calling `shapviz()`, something along these lines:

```
shapviz.explain <- function(object, X = object[["feature_values"]], baseline = object[["baseline"]], collapse = NULL, ...) {
  if (inherits(object, "tibble")) {  # packageVersion("fastshap") <= "0.0.7"
    object <- as.matrix(object)
  }
  if (is.matrix(object)) {   # explain() called with shap_only=TRUE
    if (is.null(baseline)) {  # try to extract baseline attribute
      baseline <- attr(object, which = "baseline")
    }
    if (is.null(baseline)) {  # will still be NULL is missing, so check again
      warning("No baseline attribute found in ", deparse(substitute(object)),
              "; setting baseline to zero.", call. = FALSE)
      baseline <- 0
    }
    if (is.null(X)) {
      stop("Pass feature values 'X' or use 'fastshap::explain(..., shap_only = FALSE)'")
    }
    shapviz.matrix(object, X = X, baseline = baseline, collapse = collapse)
  } else {  # explain() called with shap_only=FALSE
    shapviz.matrix(object[["shapley_values"]], X = X, baseline = baseline, collapse = collapse)
  }
}
```

Since it does not require any function from {fastshap}, we even don't need to list it under "enhances". I think adding above function (and a bit more prominently in the vignette) should already do the job! What is your impression?

**Comment by bgreenwell** [comment]
Thanks @mayer79, but this will fail on matrices (i.e., when `shap_only = TRUE`) due to the default arguments. This version should work based on what you have (and tested on my end with the dev version):

```r
shapviz.explain <- function(object, X = NULL, baseline = NULL, 
                            collapse = NULL, ...) {
  if (inherits(object, "tibble")) {  # packageVersion("fastshap") <= "0.0.7"
    object <- as.matrix(object)
  }
  if (is.matrix(object)) {   # explain() called with shap_only=TRUE
    if (is.null(baseline)) {  # try to extract baseline attribute
      baseline <- attr(object, which = "baseline")
    }
    if (is.null(baseline)) {  # will still be NULL is missing, so check again
      warning("No baseline attribute found in ", deparse(substitute(object)),
              "; setting baseline to zero.", call. = FALSE)
      baseline <- 0
    }
    if (is.null(X)) {
      stop("No featue values found. Pass feature values via 'X' or use ",
           "'fastshap::explain(..., shap_only = FALSE)'", call. = FALSE)
    }
    shapviz.matrix(object, X = X, baseline = baseline, collapse = collapse)
  } else {  # explain() called with shap_only=FALSE
    shapviz.matrix(object[["shapley_values"]], X = object[["feature_values"]], 
                   baseline = object[["baseline"]], collapse = collapse)
  }
}
```
And to your point on "Enhances", yes, **shapviz** does not require any function from **fastshap**, so I would certainly not add it to "Suggests", but **shapviz** provides new functionality (or enhances) **fastshap**, which is the purpose of the "ENhances" field. Doesn't really matter though, and I plan to add **shapviz** plotting to the new vignette Ill start on soon. Just let me know when you pull the above modification in.

**Comment by mayer79** [comment]
Ahh, indeed, thanks for pointing this out!

To allow passing another `X` (e.g., with clipped outlier) we can modify the last part by:

```
shapviz.matrix(
  object[["shapley_values"]], 
  X = if (!is.null(X)) X else object[["feature_values"]], 
  baseline = if (!is.null(baseline)) baseline else object[["baseline"]], 
  collapse = collapse
)
```

**Comment by bgreenwell** [comment]
Let me know if you’d prefer a PR or to add it on your end.

**Comment by mayer79** [comment]
You can have a beer while I will do the PR (tomorrow or on Friday) 😊 Gesendet von Mail für Windows Von: Brandon GreenwellGesendet: Mittwoch, 3. Mai 2023 20:41An: ModelOriented/shapvizCc: Michael Mayer; MentionBetreff: Re: [ModelOriented/shapviz] Upcoming changes to fastshap (Issue #34) Let me know if you’d prefer a PR or to add it on your end.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by mayer79** [comment]
Done in https://github.com/ModelOriented/shapviz/pull/84
